name: pnd
channels:  
  - conda-forge  
  - plotly
  - defaults
dependencies:
  - python>=3.8, <3.13
  - pip
  - numpy>=1.20, <2
  - scipy
  - pandas
  - matplotlib
  - plotly::plotly
  - cmcrameri
  - ipython  
  - jupyter
  - ipywidgets
  